### ISSUE TITLE
Deployment is unmarshalled with empty/null fields

### ISSUE THREAD

**Issue by nikimanoledaki** [nikimanoledaki/gitops-energy-usage#2]
Current Deployment that is created looks like this:
```
typemeta:
  kind: Deployment
  apiversion: apps/v1
objectmeta:
  name: 09-09-2022-18-17-02
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp:
    time: {}
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels:
    app: date-setter
  annotations: {}
  ownerreferences: []
  finalizers: []
  managedfields: []
spec:
  replicas: 1
  selector:
    matchlabels:
      app: date-setter
    matchexpressions: []
  template:
    objectmeta:
      name: ""
      generatename: ""
      namespace: ""
      selflink: ""
      uid: ""
      resourceversion: ""
      generation: 0
      creationtimestamp:
        time: {}
      deletiontimestamp: null
      deletiongraceperiodseconds: null
      labels:
        app: date-setter
      annotations: {}
      ownerreferences: []
      finalizers: []
      managedfields: []
    spec:
      volumes: []
      initcontainers: []
      containers:
      - name: date-setter
        image: docker.io/niki2401/date-setter:latest
        command: []
        args: []
        workingdir: ""
        ports:
        - name: ""
          hostport: 0
          containerport: 8080
          protocol: ""
          hostip: ""
        envfrom: []
        env: []
        resources:
          limits: {}
          requests: {}
        volumemounts: []
        volumedevices: []
        livenessprobe: null
        readinessprobe: null
        startupprobe: null
        lifecycle: null
        terminationmessagepath: ""
        terminationmessagepolicy: ""
        imagepullpolicy: ""
        securitycontext: null
        stdin: false
        stdinonce: false
        tty: false
      ephemeralcontainers: []
      restartpolicy: ""
      terminationgraceperiodseconds: null
      activedeadlineseconds: null
      dnspolicy: ""
      nodeselector: {}
      serviceaccountname: ""
      deprecatedserviceaccount: ""
      automountserviceaccounttoken: null
      nodename: ""
      hostnetwork: false
      hostpid: false
      hostipc: false
      shareprocessnamespace: null
      securitycontext: null
      imagepullsecrets: []
      hostname: ""
      subdomain: ""
      affinity: null
      schedulername: ""
      tolerations: []
      hostaliases: []
      priorityclassname: ""
      priority: null
      dnsconfig: null
      readinessgates: []
      runtimeclassname: null
      enableservicelinks: null
      preemptionpolicy: null
      overhead: {}
      topologyspreadconstraints: []
      sethostnameasfqdn: null
      os: null
      hostusers: null
  strategy:
    type: ""
    rollingupdate: null
  minreadyseconds: 0
  revisionhistorylimit: null
  paused: false
  progressdeadlineseconds: null
status:
  observedgeneration: 0
  replicas: 0
  updatedreplicas: 0
  readyreplicas: 0
  availablereplicas: 0
  unavailablereplicas: 0
  conditions: []
  collisioncount: null
```
